// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Introduction
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },

    // General
    {
      type: 'category',
      label: 'General',
      items: [{ type: 'autogenerated', dirName: 'general' }],
    },

    // Portal
    {
      type: 'category',
      label: 'Portal',
      items: [{ type: 'autogenerated', dirName: 'portal' }],
    },

    // Services
    {
      type: 'category',
      label: 'Services',
      items: [{ type: 'autogenerated', dirName: 'services' }],
    },

    // MasWallet
    {
      type: 'category',
      label: 'MasWallet',
      items: [
        'maswallet/introduction',
        'maswallet/getting-started',
        {
          type: 'link',
          label: 'MasWallet SDK',
          href: 'https://www.npmjs.com/package/maswallet-nodejs', 
        },
      ],
    },
  ],
};

export default sidebars;